// ISO 8583 Authorization Response structure
export interface ISO8583AuthorizationResponse {
  // Response Code - Field 39
  responseCode: string;
  
  // Response Message
  responseMessage: string;
  
  // Authorization Code - Field 38 (6 alphanumeric characters)
  authorizationCode?: string;
  
  // System Trace Audit Number - Field 11 (echoed from request)
  stan: string;
  
  // Retrieval Reference Number - Field 37 (echoed from request)
  retrievalReferenceNumber: string;
  
  // Transmission Date and Time - Field 7
  transmissionDateTime: string;
  
  // Additional Response Data - Field 44 (optional)
  additionalResponseData?: Record<string, unknown>;
}

// Common ISO 8583 Response Codes
export const ISO8583_RESPONSE_CODES = {
  APPROVED: '00',
  REFER_TO_CARD_ISSUER: '01',
  REFER_TO_CARD_ISSUER_SPECIAL: '02',
  INVALID_MERCHANT: '03',
  PICK_UP_CARD: '04',
  DO_NOT_HONOR: '05',
  ERROR: '06',
  PICK_UP_CARD_SPECIAL: '07',
  HONOR_WITH_ID: '08',
  REQUEST_IN_PROGRESS: '09',
  APPROVED_PARTIAL: '10',
  INVALID_CARD_NUMBER: '14',
  NO_SUCH_ISSUER: '15',
  APPROVED_UPDATE_TRACK_3: '16',
  CUSTOMER_CANCELLATION: '17',
  CUSTOMER_DISPUTE: '18',
  RE_ENTER_TRANSACTION: '19',
  INVALID_RESPONSE: '20',
  NO_ACTION_TAKEN: '21',
  SUSPECTED_MALFUNCTION: '22',
  UNACCEPTABLE_TRANSACTION_FEE: '23',
  FILE_UPDATE_NOT_SUPPORTED: '24',
  UNABLE_TO_LOCATE_RECORD: '25',
  DUPLICATE_FILE_UPDATE_RECORD: '26',
  FILE_UPDATE_FIELD_EDIT_ERROR: '27',
  FILE_UPDATE_FILE_LOCKED: '28',
  FILE_UPDATE_NOT_SUCCESSFUL: '29',
  FORMAT_ERROR: '30',
  BANK_NOT_SUPPORTED: '31',
  COMPLETED_PARTIALLY: '32',
  EXPIRED_CARD_PICK_UP: '33',
  SUSPECTED_FRAUD_PICK_UP: '34',
  CARD_ACCEPTOR_CONTACT_ACQUIRER_PICK_UP: '35',
  RESTRICTED_CARD_PICK_UP: '36',
  CARD_ACCEPTOR_CALL_ACQUIRER_SECURITY_PICK_UP: '37',
  ALLOWABLE_PIN_TRIES_EXCEEDED_PICK_UP: '38',
  NO_CREDIT_ACCOUNT: '39',
  REQUESTED_FUNCTION_NOT_SUPPORTED: '40',
  LOST_CARD_PICK_UP: '41',
  NO_UNIVERSAL_ACCOUNT: '42',
  STOLEN_CARD_PICK_UP: '43',
  NO_INVESTMENT_ACCOUNT: '44',
  INSUFFICIENT_FUNDS: '51',
  NO_CHECKING_ACCOUNT: '52',
  NO_SAVINGS_ACCOUNT: '53',
  EXPIRED_CARD: '54',
  INCORRECT_PIN: '55',
  NO_CARD_RECORD: '56',
  TRANSACTION_NOT_PERMITTED_TO_CARDHOLDER: '57',
  TRANSACTION_NOT_PERMITTED_TO_TERMINAL: '58',
  SUSPECTED_FRAUD: '59',
  CARD_ACCEPTOR_CONTACT_ACQUIRER: '60',
  EXCEEDS_WITHDRAWAL_AMOUNT_LIMIT: '61',
  RESTRICTED_CARD: '62',
  SECURITY_VIOLATION: '63',
  ORIGINAL_AMOUNT_INCORRECT: '64',
  EXCEEDS_WITHDRAWAL_FREQUENCY_LIMIT: '65',
  CARD_ACCEPTOR_CALL_ACQUIRER_SECURITY: '66',
  HARD_CAPTURE_PICK_UP: '67',
  RESPONSE_RECEIVED_TOO_LATE: '68',
  ALLOWABLE_NUMBER_OF_PIN_TRIES_EXCEEDED: '75',
  INVALID_ACCOUNT: '76',
  INVALID_ACCOUNT_SPECIFIED: '77',
  INVALID_ACCOUNT_SPECIFIED_GENERAL: '78',
  ALREADY_REVERSED: '79',
  NO_FINANCIAL_IMPACT: '80',
  CRYPTOGRAPHIC_FAILURE: '81',
  NEGATIVE_CAM_DCCV_ARQC_VALIDATION: '82',
  UNABLE_TO_VERIFY_PIN: '83',
  INVALID_AUTHORIZATION_LIFE_CYCLE: '84',
  NOT_DECLINED_VALID_FOR_ALL_ZERO_AMOUNT: '85',
  PIN_VALIDATION_NOT_POSSIBLE: '86',
  PURCHASE_AMOUNT_ONLY_NO_CASH_BACK_ALLOWED: '87',
  CRYPTOGRAPHIC_FAILURE_MAC: '88',
  UNACCEPTABLE_PIN_TRANSACTION_DECLINED_RETRY: '89',
  CUTOFF_IN_PROGRESS: '90',
  ISSUER_OR_SWITCH_INOPERATIVE: '91',
  FINANCIAL_INSTITUTION_OR_INTERMEDIATE_NETWORK_FACILITY_CANNOT_BE_FOUND: '92',
  TRANSACTION_CANNOT_BE_COMPLETED_VIOLATION_OF_LAW: '93',
  DUPLICATE_TRANSMISSION: '94',
  RECONCILE_ERROR: '95',
  SYSTEM_MALFUNCTION: '96',
  RECONCILIATION_TOTALS_RESET: '97',
  MAC_ERROR: '98',
  RESERVED_FOR_NATIONAL_USE: '99',
} as const;
